# ampm-analysis configuration


[paths]
source    = 'C:\Users\ohp460\Documents\Code\ampm-analysis\data\JR299_OHP_Ti-Sterling\[3] Export Packets'
stl       = 'C:\Users\ohp460\Documents\Code\ampm-analysis\data\JR299_OHP_Ti-Sterling\JR299_fullplate.stl'
parts_csv = 'C:\Users\ohp460\Documents\Code\ampm-analysis\data\JR299_OHP_Ti-Sterling\JR299_sterling_parts.csv'

[build]
layer_thickness = 0.03  # mm